In [38]:
import numpy as np
grid = np.arange(1,10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
x = np.array([1,2,3])
x.reshape((1,3))

array([[1, 2, 3]])

In [26]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [28]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [30]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [46]:
z = np.concatenate([x, x[::-1]])
print(z)

[1 2 3 3 2 1]


In [48]:
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
np.hstack([grid,x[:,np.newaxis]])

array([[1, 2, 3, 1],
       [4, 5, 6, 2],
       [7, 8, 9, 3]])

In [57]:
xsplit = [1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(xsplit, [3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [63]:
sample = np.arange(1,13)
np.multiply.outer(sample, sample)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132],
       [ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144]])

In [95]:
rng = np.random.default_rng()
sample1 = rng.random(100000)
%timeit np.min(sample1)
%timeit sample1.min()

114 μs ± 2.86 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
111 μs ± 3.44 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [150]:
sample2 = rng.integers(0,10,(4,4))
print(sample2)

[[6 1 7 6]
 [6 2 0 6]
 [9 3 6 1]
 [0 6 6 6]]


In [198]:
len(sample2.reshape(4,4))

4